/* ───────────────────────────────────────────────────────────────────────────
   Las novedades de la web — la ÚNICA fuente.

   Las dos páginas (español e inglés) leen de aquí. Escribir una novedad es
   añadir un objeto arriba del array, con su texto en los dos idiomas; no hay
   un segundo sitio que actualizar y por tanto no hay un segundo sitio que se
   quede viejo, que es como se llega a dos páginas contando cosas distintas.

   - `fecha`     en ISO (AAAA-MM-DD). La página la escribe en el formato de
                 cada idioma, así que aquí va siempre igual.
   - `etiqueta`  una palabra. Sale como píldora roja al lado de la fecha.
   - `titulo`    una línea.
   - `cuerpo`    uno o dos párrafos. Se acepta HTML sencillo (<b>, <i>, <a>).

   Lo más nuevo va ARRIBA.
   ─────────────────────────────────────────────────────────────────────────── */

const NOVEDADES = [

  {
    fecha: "2026-08-31",
    etiqueta: { es: "Arte",    en: "Art" },
    titulo: {
      es: "La portada, generada por el propio juego",
      en: "The store art, generated by the game itself"
    },
    cuerpo: {
      es: "La máscara de zorro que preside el menú no es un dibujo importado: la " +
          "dibuja el juego con un comando, y del mismo generador salen el icono de " +
          "la ventana y las imágenes de la ficha de la tienda. El día que cambie la " +
          "marca cambian todas a la vez, que es la única manera de que ninguna " +
          "acabe enseñando algo que ya no existe.",
      en: "The fox mask on the title screen isn't an imported drawing: the game " +
          "renders it from a command, and the window icon and the store artwork come " +
          "out of that same generator. The day the mark changes they all change at " +
          "once, which is the only way none of them ends up showing something that " +
          "isn't there any more."
    }
  },

  {
    fecha: "2026-08-31",
    etiqueta: { es: "Idiomas", en: "Languages" },
    titulo: {
      es: "El juego se puede jugar entero en cinco idiomas",
      en: "The whole game is playable in five languages"
    },
    cuerpo: {
      es: "Español, inglés, alemán, francés e italiano, con los 1.235 textos del " +
          "juego traducidos: los diálogos, los paneles, los nombres de las 540 " +
          "cartas y sus ataques. Los kanji de los sitios no se traducen — " +
          "<b>買取強化</b> es un nombre, no una etiqueta, y aprenderlo es parte de " +
          "aprender el barrio.",
      en: "Spanish, English, German, French and Italian, with all 1,235 strings " +
          "translated: dialogue, panels, the names of the 540 cards and their " +
          "attacks. Place-name kanji stay as they are — <b>買取強化</b> is a name, " +
          "not a label, and learning it is part of learning the neighbourhood."
    }
  },

  {
    fecha: "2026-08-30",
    etiqueta: { es: "Mundo",   en: "World" },
    titulo: {
      es: "La pantalla de inicio pasea por seis sitios",
      en: "The title screen now tours six places"
    },
    cuerpo: {
      es: "Enseñaba una sola calle en bucle, y detrás había un cruce con torres de " +
          "neón, un pasaje cubierto de farolillos, un parque con cerezos y un " +
          "callejón de dos metros y medio. Ahora son seis tomas y la última se " +
          "para delante del local vacío que se alquila — que es adonde va todo esto.",
      en: "It used to loop one street, and behind it there was a neon crossing, a " +
          "covered arcade strung with lanterns, a park with cherry trees and an " +
          "alley two and a half metres wide. Six shots now, and the last one stops " +
          "in front of the empty shop for rent — which is where all of this is going."
    }
  },

  {
    fecha: "2026-08-29",
    etiqueta: { es: "Campaña", en: "Campaign" },
    titulo: {
      es: "La campaña se puede terminar de principio a fin",
      en: "The campaign can be finished end to end"
    },
    cuerpo: {
      es: "Los cuatro actos están encadenados: del cuarto con las cajas de la " +
          "abuela al traspaso del local, pasando por las convenciones y por el día " +
          "en que Kenji entra por tu puerta. Antes se llegaba al final del segundo " +
          "acto y el juego se quedaba ahí sin decirlo.",
      en: "All four acts are wired together now: from the room full of your " +
          "grandmother's boxes to signing the lease, by way of the conventions and " +
          "the day Kenji walks through your door. Before this, you reached the end " +
          "of act two and the game quietly stopped."
    }
  }

];
